Refactoring project

diff --git a/Cloudformation.yaml b/Cloudformation.yaml
--- a/Cloudformation.yaml
+++ b/Cloudformation.yaml
@@ -13,10 +13,14 @@ Resources:
         Fn::Base64: 
           !Sub |
             #!/bin/bash -xe
+
+            #Installing Elasticsearch
             apt-get update -y
             wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
             echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | tee /etc/apt/sources.list.d/elastic-7.x.list
             apt-get update && apt-get install elasticsearch
+            
+            #Setting env Variables and adjusting elasticsearch config
             IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
             echo "IP is: $IP"
             echo "network.host: $IP" >> /etc/elasticsearch/elasticsearch.yml
@@ -24,11 +28,49 @@ Resources:
             echo "discovery.type: single-node" >> /etc/elasticsearch/elasticsearch.yml
             echo "cluster.name: Metrics-project" >> /etc/elasticsearch/elasticsearch.yml
             systemctl start elasticsearch.service
+            
+            #Downloading and starting python http server
+            curl -o /home/ubuntu/server.py https://raw.githubusercontent.com/Sebziel/metrics-project/master/server.py
+            python3 /home/ubuntu/server.py > /dev/null 2>&1 &
+            
+            # Function to check if Kibana is up - It's required for metricbeat to function correctly to start Kibana first.
+            wait_for_kibana() {
+              local kibana_url="http://$IP:5601"
+              local max_attempts=30
+              local attempt=1
+            
+              echo "Waiting for Kibana to be available at $kibana_url..."
+            
+              while [ $attempt -le $max_attempts ]; do
+                # Follow redirects with -L and check for a successful response
+                if curl -s -L -o /dev/null -w "%{http_code}" $kibana_url | grep "200\|302" > /dev/null; then
+                  echo "Kibana is up and running!"
+                  return 0
+                else
+                  echo "Attempt $attempt/$max_attempts: Kibana is not available yet. Retrying in 5 seconds..."
+                  attempt=$((attempt + 1))
+                  sleep 5
+                fi
+              done
+            
+              echo "Kibana did not become available after $max_attempts attempts."
+              return 1
+            }
+            
+            #Installing and adjusting kibana config
             apt-get install kibana
             echo "server.host: $IP" >> /etc/kibana/kibana.yml
             echo "elasticsearch.hosts: http://$IP:9200" >> /etc/kibana/kibana.yml
             systemctl start kibana
-            apt-get install metricbeat apt-transport-https python3-pip stress -y
+            #Adding sleep to allow to load kibana before setting up dashboards
+            
+            if ! wait_for_kibana; then
+              echo "Failed to start Kibana. Exiting."
+              exit 1
+            fi
+            
+            #Installing and adjusting metricbeat config, installing python utilities
+            apt-get install metricbeat -y
             sed -i "s/#host: \"localhost:5601\"/host: \"http:\/\/$IP:5601\"/g" /etc/metricbeat/metricbeat.yml
             sed -i "s/hosts: \[\"localhost:9200\"\]/hosts: \[\"$IP:9200\"\]/g" /etc/metricbeat/metricbeat.yml
             metricbeat modules enable prometheus
@@ -39,36 +81,7 @@ Resources:
             echo "  metrics_path: /metrics/gc" >> /etc/metricbeat/modules.d/prometheus.yml
             systemctl start metricbeat
             echo "Loading Dashboard from metricbeat to kibana"
-            sleep 15
             metricbeat setup --dashboards
-            
-  MyJavaInstance:
-    Type: 'AWS::EC2::Instance'
-    Properties:
-      InstanceType: t2.medium
-      Tags:
-      - Key: Name
-        Value: JavaApp
-      ImageId: ami-0e001c9271cf7f3b9 # Replace with the actual AMI ID for Ubuntu
-      SecurityGroups:
-        - !Ref InstanceSecurityGroup
-      UserData:
-        Fn::Base64: 
-          !Sub |
-            #!/bin/bash -xe
-            apt-get update -y
-            wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
-            echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | tee /etc/apt/sources.list.d/elastic-7.x.list
-            apt-get update -y
-            apt-get install nano iputils-ping dnsutils openjdk-17-jdk maven git curl metricbeat -y >> /home/ubuntu/tools_install.log
-            cd /home/ubuntu/
-            git clone https://github.com/spring-projects/spring-petclinic.git >> /home/ubuntu/git_clone.log
-            echo "Running pwd and ls":
-            pwd
-            ls -ltr
-            cd spring-petclinic
-            ./mvnw package >> /home/ubuntu/mvn.log
-
 
   InstanceSecurityGroup:
     Type: 'AWS::EC2::SecurityGroup'
